//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1ERParcialPRG3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mDepartamento
    {
        public int IdDepto { get; set; }
        public string DeptoNombre { get; set; }
        public int Activo { get; set; }
    }
}
